-- MySQL Script generated by MySQL Workbench
-- Wed Nov 14 15:27:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Felhasznalok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Felhasznalok` (
  `idFelhasznalok` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `jelszo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFelhasznalok`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
;


-- -----------------------------------------------------
-- Table `mydb`.`Auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auto` (
  `idAuto` INT NOT NULL,
  `Nev` VARCHAR(45) NULL,
  `muszaki_lejarat` DATETIME NULL,
  `kotelezo_biztositas_lejarat` DATETIME NULL,
  `fakultativ_biztositas_lejarat` DATETIME NULL,
  `kmOra` INT NULL,
  `Auto_felelos` INT NOT NULL,
  PRIMARY KEY (`idAuto`, `Auto_felelos`),
  INDEX `fk_Auto_Felhasznalok1_idx` (`Auto_felelos` ASC) ,
  CONSTRAINT `fk_Auto_Felhasznalok1`
    FOREIGN KEY (`Auto_felelos`)
    REFERENCES `mydb`.`Felhasznalok` (`idFelhasznalok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`Utazas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utazas` (
  `idUtazas` INT NOT NULL,
  `Sofor` INT NULL,
  `indulas` DATETIME NULL,
  `haza_erkezes` DATETIME NULL,
  `Celalomas` VARCHAR(45) NULL,
  `Utasok_szama` INT NULL,
  `Utazas_celja` VARCHAR(45) NULL,
  `Alapot` INT NULL,
  `Auto` INT NOT NULL,
  `Igenylo` INT NOT NULL,
  PRIMARY KEY (`idUtazas`, `Auto`, `Igenylo`),
  INDEX `fk_Utazas_Auto1_idx` (`Auto` ASC) ,
  INDEX `fk_Utazas_Felhasznalok1_idx` (`Igenylo` ASC) ,
  CONSTRAINT `fk_Utazas_Auto1`
    FOREIGN KEY (`Auto`)
    REFERENCES `mydb`.`Auto` (`idAuto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utazas_Felhasznalok1`
    FOREIGN KEY (`Igenylo`)
    REFERENCES `mydb`.`Felhasznalok` (`idFelhasznalok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`Utazo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utazo` (
  `idUtazo` INT NOT NULL,
  `Nev` VARCHAR(45) NULL,
  `Utazo_tipus` VARCHAR(45) NULL,
  `Utazas_id` INT NOT NULL,
  PRIMARY KEY (`idUtazo`, `Utazas_id`),
  INDEX `fk_Utazo_Utazas1_idx` (`Utazas_id` ASC) ,
  CONSTRAINT `fk_Utazo_Utazas1`
    FOREIGN KEY (`Utazas_id`)
    REFERENCES `mydb`.`Utazas` (`idUtazas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `mydb`.`Felhasznalo_tipus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Felhasznalo_tipus` (
  `Felhasznalo_id` INT NOT NULL,
  `Dekan_hivatal` INT NULL,
  `Gazdasagi_igazgato` INT NULL,
  `Garazs_felelos` INT NULL,
  `Auto_felelos` INT NULL,
  `Auto_igenylo` INT NULL,
  `Vezeto` INT NULL,
  PRIMARY KEY (`Felhasznalo_id`),
  INDEX `fk_Felhasznalo_tipus_Felhasznalok1_idx` (`Felhasznalo_id` ASC) ,
  CONSTRAINT `fk_Felhasznalo_tipus_Felhasznalok1`
    FOREIGN KEY (`Felhasznalo_id`)
    REFERENCES `mydb`.`Felhasznalok` (`idFelhasznalok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
